### ISSUE TITLE
SES Rule Sets Are Manual

### ISSUE THREAD

**Issue by emileswarts** [alphagov/govwifi-terraform#82]
There is only allowed to be one active rule set for SES.

This can be achieved by Terraform but once applied in one environment / region, subsequent applies will fail with an error.

Hence creating the rule set is still a manual step.

Solution to this down the line could be to have a new global top level Terraform which isn't tied to environment or region.  It will be run before any of the other Terraform is run.

**Comment by adrianclay** [comment]
See #81 for more information.
